# ChocoPy RISC-V Assembly
# Generated by ChocoPy Compiler

.data


.text
.global main

add:
    # Function: add
    addi sp, sp, -16
    sw ra, 12(sp)
    sw fp, 8(sp)
    addi fp, sp, 16
    lw a0, -4(fp)
    # Load a
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, -8(fp)
    # Load b
    lw a1, 0(sp)
    addi sp, sp, 4
    add a0, a1, a0
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra
    # Function epilogue
    li a0, 0
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra

factorial:
    # Function: factorial
    addi sp, sp, -16
    sw ra, 12(sp)
    sw fp, 8(sp)
    addi fp, sp, 16
    lw a0, -4(fp)
    # Load n
    addi sp, sp, -4
    sw a0, 0(sp)
    li a0, 1
    lw a1, 0(sp)
    addi sp, sp, 4
    slt a0, a0, a1
    xori a0, a0, 1
    beq a0, zero, else0
    li a0, 1
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra
    j endif1
else0:
    lw a0, -4(fp)
    # Load n
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, -4(fp)
    # Load n
    addi sp, sp, -4
    sw a0, 0(sp)
    li a0, 1
    lw a1, 0(sp)
    addi sp, sp, 4
    sub a0, a1, a0
    addi sp, sp, -4
    sw a0, 0(sp)
    jal factorial
    addi sp, sp, 4
    lw a1, 0(sp)
    addi sp, sp, 4
    mul a0, a1, a0
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra
endif1:
    # Function epilogue
    li a0, 0
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra

main:
    # Undefined variable: x
    li a0, 0
    addi sp, sp, -4
    sw a0, 0(sp)
    # Undefined variable: y
    li a0, 0
    addi sp, sp, -4
    sw a0, 0(sp)
    jal add
    addi sp, sp, 8
    addi sp, sp, -4
    sw a0, -4(fp)
    # Store to result
    li a0, 5
    addi sp, sp, -4
    sw a0, 0(sp)
    jal factorial
    addi sp, sp, 4
    addi sp, sp, -4
    sw a0, -8(fp)
    # Store to fact
    lw a0, -4(fp)
    # Load result
    jal print_int
    li a0, 0
    lw a0, -8(fp)
    # Load fact
    jal print_int
    li a0, 0
    li a0, 0
    li a7, 93
    ecall

    # Built-in functions
print_int:
    li a7, 1
    ecall
    li a7, 11
    li a0, 10
    ecall
    jr ra