# ChocoPy RISC-V Assembly
# Generated by ChocoPy Compiler

.data


.text
.global main

test:
    # Function: test
    addi sp, sp, -16
    sw ra, 12(sp)
    sw fp, 8(sp)
    addi fp, sp, 16
    li a0, 5
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra
    # Function epilogue
    li a0, 0
    lw ra, 12(sp)
    lw fp, 8(sp)
    addi sp, sp, 16
    jr ra

main:
    jal test
    addi sp, sp, -4
    sw a0, -4(fp)
    # Store to result
    lw a0, -4(fp)
    # Load result
    jal print_int
    li a0, 0
    li a0, 0
    li a7, 93
    ecall

    # Built-in functions
print_int:
    li a7, 1
    ecall
    li a7, 11
    li a0, 10
    ecall
    jr ra