# ChocoPy RISC-V Assembly
# Generated by ChocoPy Compiler

.data


.text
.global main

main:
    # Undefined variable: x
    li a0, 0
    addi sp, sp, -4
    sw a0, 0(sp)
    # Undefined variable: y
    li a0, 0
    lw a1, 0(sp)
    addi sp, sp, 4
    add a0, a1, a0
    addi sp, sp, -4
    sw a0, -4(fp)
    # Store to z
    lw a0, -4(fp)
    # Load z
    jal print_int
    li a0, 0
    li a0, 0
    li a7, 93
    ecall

    # Built-in functions
print_int:
    li a7, 1
    ecall
    li a7, 11
    li a0, 10
    ecall
    jr ra